### ISSUE TITLE
Could not compile 'groot'

### ISSUE THREAD

**Issue by peter-hristov** [thiagopnts/groot#1]
With cargo version cargo 0.0.1-pre-nightly and rustc 1.0.0-dev on arch linux I'm getting:

Compiling groot v0.0.1 (file:///home/peter/Projects/rust/groot)
src/operations.rs:2:10: 2:15 error: unknown `derive` trait: `Debug`
src/operations.rs:2 #[derive(Debug, PartialEq)]
                             ^~~~~
error: aborting due to previous error
Could not compile `groot`.

**Comment by coreyhaines** [comment]
:( I get the same error. I'm running the 1.0.0-alpha of rust from http://www.rust-lang.org/install.html

**Comment by oderwat** [comment]
You need to use 1.0.0-nightly instead of 1.0.0-alpha.
I just compiled it with: rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)

**Comment by thiagopnts** [comment]
You're right, I'm using `rustc 1.0.0-nightly (92ff8ea52 2015-01-27 23:08:13 +0000)`
I'll mention this on readme, thanks!
