### ISSUE TITLE
Bad documentation?

### ISSUE THREAD

**Issue by olivierrr** [thiagopnts/groot#2]
`cat helloworld.groot | sort | uniq`
- I AM GROOOT
- i am groot # not on documentation
- I am groot
- I am Groot
- I AM GROOT
- I'm Groot  # not on documentation
- We are Groot

**Comment by olivierrr** [comment]
made a little [brainf*ck to groot compiler](https://gist.github.com/olivierrr/7ef676c28d6c428ad0a7)

[mandlebrot set in groot lang](https://gist.github.com/olivierrr/d97d4d2689435ea91283) 
![mandlebrot_groot](https://cloud.githubusercontent.com/assets/8010834/5990913/e4849f60-a97f-11e4-84d8-c09776ebcfc1.png)

Thanks for the fun!

**Comment by thiagopnts** [comment]
Nice! Can I add it as an example?

**Comment by olivierrr** [comment]
@thiagopnts :+1:

**Comment by thiagopnts** [comment]
Awesome, thanks!
