### ISSUE TITLE
Viewing README.md causes subject to die.

### ISSUE THREAD

**Issue by ghost** [thiagopnts/groot#6]
Steps to reproduce:
1.) Open thiagopnts/groot/README.md in any text-displaying software that renders to a display device.
2.) Place subject in front of display device.

Within seconds, subject experiences rapid convulsions of the diaphragm. Convulsions continue with increasing frequency as subject continues reading README.md. Upon reaching the Building and Running instructions, subject is in spasms. Death follows shortly. 

This issue has been reproduced locally with 100% accuracy. Patches deemed intractable. Please advise.

**Comment by thiagopnts** [comment]
marked as a `wontfix` :dancer:
